const fs = require('fs');
const path = require('path');

const list = [
  {slug:"mortgage-calculator",title:"Mortgage Calculator",logic_type:"loan",type:"real-estate",icon:"🏠",description:"Calculate mortgage payments.",intro:"Estimate monthly costs.",inputs:{p_label:"Loan Amount",r_label:"Rate %",t_label:"Years"},meta_title_us:"US Mortgage Calc",h1_title_us:"US Mortgage Calculator",article_body_us:"<p>Mortgage details.</p>"},
  {slug:"car-loan-calculator",title:"Car Loan Calculator",logic_type:"loan",type:"auto",icon:"🚗",description:"Calculate car payments.",intro:"Estimate car loan.",inputs:{p_label:"Car Price",r_label:"Rate %",t_label:"Years"},meta_title_us:"Car Loan Calc",h1_title_us:"Car Loan Calculator",article_body_us:"<p>Car loan details.</p>"},
  {slug:"personal-loan-calculator",title:"Personal Loan Calculator",logic_type:"loan",type:"personal",icon:"💸",description:"Personal loan payments.",intro:"Plan repayment.",inputs:{p_label:"Loan Amount",r_label:"Rate %",t_label:"Years"},meta_title_us:"Personal Loan Calc",h1_title_us:"Personal Loan Calculator",article_body_us:"<p>Personal loan details.</p>"},
  {slug:"debt-payoff-calculator",title:"Debt Payoff",logic_type:"loan",type:"debt",icon:"💳",description:"Plan debt freedom.",intro:"Estimate payoff.",inputs:{p_label:"Debt Balance",r_label:"Rate %",t_label:"Months"},meta_title_us:"Debt Payoff",h1_title_us:"Debt Payoff Calculator",article_body_us:"<p>Debt details.</p>"},
  {slug:"roi-calculator",title:"ROI Calculator",logic_type:"roi",type:"business",icon:"📈",description:"Calculate ROI.",intro:"Measure profitability.",inputs:{c_label:"Invested",v_label:"Returned"},meta_title_us:"ROI Calculator",h1_title_us:"ROI Calculator",article_body_us:"<p>ROI details.</p>"},
  {slug:"profit-margin-calculator",title:"Profit Margin",logic_type:"profit",type:"business",icon:"💼",description:"Calculate margins.",intro:"Check profit %.",inputs:{c_label:"Cost",v_label:"Price"},meta_title_us:"Profit Margin",h1_title_us:"Profit Margin Calculator",article_body_us:"<p>Margin details.</p>"},
  {slug:"cash-flow-calculator",title:"Cash Flow",logic_type:"simple_diff",type:"business",icon:"📊",description:"Income vs Expenses.",intro:"Analyze flow.",inputs:{v1_label:"Income",v2_label:"Expenses"},meta_title_us:"Cash Flow",h1_title_us:"Cash Flow Calculator",article_body_us:"<p>Cash flow details.</p>"},
  {slug:"compound-interest-calculator",title:"Compound Interest",logic_type:"growth",type:"savings",icon:"💰",description:"Calculate compound growth.",intro:"See money grow.",inputs:{p_label:"Principal",r_label:"Rate %",t_label:"Years"},meta_title_us:"Compound Interest",h1_title_us:"Compound Interest Calculator",article_body_us:"<p>Growth details.</p>"},
  {slug:"inflation-calculator",title:"Inflation Calculator",logic_type:"growth",type:"economic",icon:"📉",description:"Inflation impact.",intro:"Buying power check.",inputs:{p_label:"Current Cost",r_label:"Inflation %",t_label:"Years"},meta_title_us:"Inflation Calc",h1_title_us:"Inflation Calculator",article_body_us:"<p>Inflation details.</p>"},
  {slug:"savings-goal-calculator",title:"Savings Goal",logic_type:"growth",type:"savings",icon:"🎯",description:"Plan savings.",intro:"Reach your goal.",inputs:{p_label:"Start Balance",r_label:"Rate %",t_label:"Years"},meta_title_us:"Savings Goal",h1_title_us:"Savings Goal Calculator",article_body_us:"<p>Savings details.</p>"},
  {slug:"401k-calculator",title:"401k Calculator",logic_type:"growth",type:"retirement",icon:"👴",description:"Retirement savings.",intro:"Project 401k.",inputs:{p_label:"Balance",r_label:"Return %",t_label:"Years"},meta_title_us:"401k Calculator",h1_title_us:"401k Calculator",article_body_us:"<p>Retirement details.</p>"},
  {slug:"college-savings-calculator",title:"College Savings",logic_type:"growth",type:"savings",icon:"🎓",description:"Plan for tuition.",intro:"Save for college.",inputs:{p_label:"Savings",r_label:"Return %",t_label:"Years"},meta_title_us:"College Savings",h1_title_us:"College Savings Calculator",article_body_us:"<p>College details.</p>"},
  {slug:"stock-return-calculator",title:"Stock Return",logic_type:"roi",type:"investing",icon:"🐂",description:"Stock profits.",intro:"Measure returns.",inputs:{c_label:"Buy Price",v_label:"Sell Price"},meta_title_us:"Stock Return",h1_title_us:"Stock Return Calculator",article_body_us:"<p>Stock details.</p>"},
  {slug:"tax-equivalent-yield-calculator",title:"Tax Equivalent Yield",logic_type:"percentage",type:"investing",icon:"🏛️",description:"Compare yields.",intro:"Calculate TEY.",inputs:{v1_label:"Tax-Free Yield",v2_label:"Tax Rate (0.x)"},meta_title_us:"Tax Equivalent",h1_title_us:"TEY Calculator",article_body_us:"<p>TEY details.</p>"},
  {slug:"present-value-calculator",title:"Present Value",logic_type:"growth",type:"investing",icon:"🕰️",description:"Calculate PV.",intro:"Value today.",inputs:{p_label:"Future Value",r_label:"Discount %",t_label:"Years"},meta_title_us:"Present Value",h1_title_us:"PV Calculator",article_body_us:"<p>PV details.</p>"},
  {slug:"future-value-calculator",title:"Future Value",logic_type:"growth",type:"investing",icon:"🚀",description:"Calculate FV.",intro:"Estimate future.",inputs:{p_label:"Present Value",r_label:"Rate %",t_label:"Years"},meta_title_us:"Future Value",h1_title_us:"FV Calculator",article_body_us:"<p>FV details.</p>"},
  {slug:"rental-yield-calculator",title:"Rental Yield",logic_type:"roi",type:"real-estate",icon:"🔑",description:"Property yield.",intro:"Rental profit.",inputs:{c_label:"Cost",v_label:"Annual Rent"},meta_title_us:"Rental Yield",h1_title_us:"Rental Yield Calculator",article_body_us:"<p>Rental details.</p>"},
  {slug:"net-worth-calculator",title:"Net Worth",logic_type:"simple_diff",type:"personal",icon:"🏦",description:"Assets - Liabilities.",intro:"Find net worth.",inputs:{v1_label:"Assets",v2_label:"Liabilities"},meta_title_us:"Net Worth",h1_title_us:"Net Worth Calculator",article_body_us:"<p>Net worth details.</p>"},
  {slug:"debt-to-income-ratio-calculator",title:"DTI Calculator",logic_type:"percentage",type:"personal",icon:"⚖️",description:"Calculate DTI.",intro:"Check eligibility.",inputs:{v1_label:"Monthly Debt",v2_label:"Monthly Income"},meta_title_us:"DTI Calculator",h1_title_us:"DTI Calculator",article_body_us:"<p>DTI details.</p>"},
  {slug:"tip-calculator",title:"Tip Calculator",logic_type:"percentage",type:"personal",icon:"🍽️",description:"Calculate tips.",intro:"Determine tip.",inputs:{v1_label:"Bill",v2_label:"Tip %"},meta_title_us:"Tip Calculator",h1_title_us:"Tip Calculator",article_body_us:"<p>Tip details.</p>"}
];

if (!fs.existsSync('src/data')) fs.mkdirSync('src/data', { recursive: true });
fs.writeFileSync('src/data/calculators.json', JSON.stringify(list, null, 2));
console.log("✅ DATABASE REBUILT SUCCESSFULLY");